name: Run Survey Bot via API

on:
  repository_dispatch:
    types: [run-survey] # tÃªn event

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: datly/bot-survey
          token: ${{ secrets.GH_PAT }}
          ref: main

      # - name: Env setup
      #   run: mv .github/env/.env.dev .env

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          token: ${{ secrets.GH_PAT }}
          cache: 'npm'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Run npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Run bot
        run: |
          echo "Environment: ${{ github.event.client_payload.env }}"
          echo "Answer: ${{ github.event.client_payload.answer }}"

          node survey-cub.js "${{ github.event.client_payload.trackingId }}"
